# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GOSWAGGERCODEGENCLIENT_PHONY
	unset GOSWAGGERCODEGENCLIENT_PHONY_CLEAN
	if [ "${HAVE_06_SWAGGERCODEGEN}" = "1" ]; then
		export GOSWAGGERCODEGENCLIENT_NAME="swaggercodegen_client"
		export GOSWAGGERCODEGENCLIENT="$1"
		export GOSWAGGERCODEGENCLIENT_OBJS_DIR=
		export GOSWAGGERCODEGENCLIENT_BIN="${RUNTIME_BIN}/${GOSWAGGERCODEGENCLIENT_NAME}${BINSUFFIX}"
		export GOSWAGGERCODEGENCLIENT_BIN_CLEAN="${GOSWAGGERCODEGENCLIENT_BIN}_clean"
		export GOSWAGGERCODEGENCLIENT_PHONY="GOSWAGGERCODEGENCLIENT"
		export GOSWAGGERCODEGENCLIENT_PHONY_DEV="GOSWAGGERCODEGENCLIENT_DEV"
		export GOSWAGGERCODEGENCLIENT_PHONY_CLEAN="GOSWAGGERCODEGENCLIENT_CLEAN"
		export GOSWAGGERCODEGENCLIENT_CFLAGS=
		export GOSWAGGERCODEGENCLIENT_LDFLAGS=
		echo "GOSWAGGERCODEGENCLIENT=${GOSWAGGERCODEGENCLIENT}"
	fi

fi


