# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GRPCHELLO_PHONY
	unset GRPCHELLO_PHONY_DEV
	unset GRPCHELLO_PHONY_CLEAN
	if [ "${HAVE_03_GRPCHELLO}" = "1" ]; then
		export GRPCHELLO="$1"
		export GRPCHELLO_PHONY="GRPCHELLO"
		export GRPCHELLO_PHONY_DEV="GRPCHELLO_DEV"
		export GRPCHELLO_PHONY_CLEAN="GRPCHELLO_CLEAN"
		echo "GRPCHELLO=${GRPCHELLO}"
		
		export BINGRPCHELLOCLIENT_NAME="grpchelloclient"
		export BINGRPCHELLOCLIENT="$1"
		export BINGRPCHELLOCLIENT_OBJS_DIR=${RUNTIME_OBJS}${BINGRPCHELLOCLIENT/${ROOT}/""}
		export BINGRPCHELLOCLIENT_BIN="${RUNTIME_BIN}/${BINGRPCHELLOCLIENT_NAME}${BINSUFFIX}"
		export BINGRPCHELLOCLIENT_BIN_CLEAN="${BINGRPCHELLOCLIENT_BIN}_clean"
		export BINGRPCHELLOCLIENT_PHONY="BINGRPCHELLOCLIENT"
		export BINGRPCHELLOCLIENT_PHONY_DEV="BINGRPCHELLOCLIENT_DEV"
		export BINGRPCHELLOCLIENT_PHONY_CLEAN="BINGRPCHELLOCLIENT_CLEAN"
		export BINGRPCHELLOCLIENT_CFLAGS=
		export BINGRPCHELLOCLIENT_LDFLAGS=
		echo "BINGRPCHELLOCLIENT=${BINGRPCHELLOCLIENT}"

		export BINGRPCHELLOSERVER_NAME="grpchelloserver"
		export BINGRPCHELLOSERVER="$1"
		export BINGRPCHELLOSERVER_OBJS_DIR=${RUNTIME_OBJS}${BINGRPCHELLOSERVER/${ROOT}/""}
		export BINGRPCHELLOSERVER_BIN="${RUNTIME_BIN}/${BINGRPCHELLOSERVER_NAME}${BINSUFFIX}"
		export BINGRPCHELLOSERVER_BIN_CLEAN="${BINGRPCHELLOSERVER_BIN}_clean"
		export BINGRPCHELLOSERVER_PHONY="BINGRPCHELLOSERVER"
		export BINGRPCHELLOSERVER_PHONY_DEV="BINGRPCHELLOSERVER_DEV"
		export BINGRPCHELLOSERVER_PHONY_CLEAN="BINGRPCHELLOSERVER_CLEAN"
		export BINGRPCHELLOSERVER_CFLAGS=
		export BINGRPCHELLOSERVER_LDFLAGS=
		echo "BINGRPCHELLOSERVER=${BINGRPCHELLOSERVER}"

		export HAVE_PBGRPCHELLO=1
		export HAVE_GO_GRPCHELLO=1
	fi
fi


