/*
 * Sample API
 *
 * Production: http://api.example.com/v1  Staging: http://staging-api.example.com/v1 
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserFriends struct {

	UserId int32 `json:"userId,omitempty"`

	Account string `json:"account,omitempty"`

	Name *UserName `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Location string `json:"location,omitempty"`
}
