# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset SWAGGERCODEGENSERVER_PHONY
	unset SWAGGERCODEGENSERVER_PHONY_CLEAN
	if [ "${HAVE_06_SWAGGERCODEGEN}" = "1" ]; then
		# Gen openapi go server stub
		export SWAGGERCODEGEN_NAME="swaggercodegen"
		export SWAGGERCODEGEN="$1"
		export SWAGGERCODEGEN_OBJS_DIR=
		export SWAGGERCODEGEN_YAML="openapi/openapi_3.0_test.yaml"
		#export SWAGGERCODEGEN_CODEDIR="server"
		#export SWAGGERCODEGEN_CODEDIR_CLEAN="${SWAGGERCODEGEN_CODEDIR}_clean"
		export SWAGGERCODEGEN_PHONY="SWAGGERCODEGEN"
		export SWAGGERCODEGEN_PHONY_DEV="SWAGGERCODEGEN_DEV"
		export SWAGGERCODEGEN_PHONY_CLEAN="SWAGGERCODEGEN_CLEAN"
		export SWAGGERCODEGEN_CFLAGS=""
		export SWAGGERCODEGEN_LDFLAGS=""
		echo "SWAGGERCODEGEN=${SWAGGERCODEGEN}"
		
		# Gen openapi go server stub
		export SWAGGERCODEGENSERVER_NAME="swaggercodegen_server"
		export SWAGGERCODEGENSERVER="$1"
		export SWAGGERCODEGENSERVER_OBJS_DIR=
		export SWAGGERCODEGENSERVER_YAML="${SWAGGERCODEGEN_YAML}"
		export SWAGGERCODEGENSERVER_CODEDIR="server"
		export SWAGGERCODEGENSERVER_CODEDIR_DEV="${SWAGGERCODEGENSERVER_CODEDIR}_DEV"
		export SWAGGERCODEGENSERVER_CODEDIR_CLEAN="${SWAGGERCODEGENSERVER_CODEDIR}_clean"
		export SWAGGERCODEGENSERVER_PHONY="SWAGGERCODEGENSERVER"
		export SWAGGERCODEGENSERVER_PHONY_DEV="SWAGGERCODEGENSERVER_DEV"
		export SWAGGERCODEGENSERVER_PHONY_CLEAN="SWAGGERCODEGENSERVER_CLEAN"
		export SWAGGERCODEGENSERVER_CFLAGS=""
		export SWAGGERCODEGENSERVER_LDFLAGS=""
		echo "SWAGGERCODEGENSERVER=${SWAGGERCODEGENSERVER}"

		# Gen openapi go client sdk
		export SWAGGERCODEGENCLIENT_NAME="swaggercodegen_client"
		export SWAGGERCODEGENCLIENT="$1"
		export SWAGGERCODEGENCLIENT_OBJS_DIR=
		export SWAGGERCODEGENCLIENT_YAML="${SWAGGERCODEGEN_YAML}"
		export SWAGGERCODEGENCLIENT_CODEDIR="client"
		export SWAGGERCODEGENCLIENT_CODEDIR_DEV="${SWAGGERCODEGENCLIENT_CODEDIR}_DEV"
		export SWAGGERCODEGENCLIENT_CODEDIR_CLEAN="${SWAGGERCODEGENCLIENT_CODEDIR}_clean"
		export SWAGGERCODEGENCLIENT_PHONY="SWAGGERCODEGENCLIENT"
		export SWAGGERCODEGENCLIENT_PHONY_DEV="SWAGGERCODEGENCLIENT_DEV"
		export SWAGGERCODEGENCLIENT_PHONY_CLEAN="SWAGGERCODEGENCLIENT_CLEAN"
		export SWAGGERCODEGENCLIENT_CFLAGS=""
		export SWAGGERCODEGENCLIENT_LDFLAGS=""
		echo "SWAGGERCODEGENCLIENT=${SWAGGERCODEGENCLIENT}"
		
		# Gen openapi html2
		export SWAGGERCODEGENHTML2_NAME="swaggercodegen_html2"
		export SWAGGERCODEGENHTML2="$1"
		export SWAGGERCODEGENHTML2_OBJS_DIR=
		export SWAGGERCODEGENHTML2_YAML="${SWAGGERCODEGEN_YAML}"
		export SWAGGERCODEGENHTML2_CODEDIR="html2"
		export SWAGGERCODEGENHTML2_CODEDIR_DEV="${SWAGGERCODEGENHTML2_CODEDIR}_DEV"
		export SWAGGERCODEGENHTML2_CODEDIR_CLEAN="${SWAGGERCODEGENHTML2_CODEDIR}_clean"
		export SWAGGERCODEGENHTML2_PHONY="SWAGGERCODEGENHTML2"
		export SWAGGERCODEGENHTML2_PHONY_DEV="SWAGGERCODEGENHTML2_DEV"
		export SWAGGERCODEGENHTML2_PHONY_CLEAN="SWAGGERCODEGENHTML2_CLEAN"
		export SWAGGERCODEGENHTML2_CFLAGS=""
		export SWAGGERCODEGENHTML2_LDFLAGS=""
		echo "SWAGGERCODEGENHTML2=${SWAGGERCODEGENHTML2}"



	fi

fi

