# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GINWEBSER_PHONY
	unset GINWEBSER_PHONY_CLEAN
	if [ "${HAVE_05_GINWEBSER}" = "1" ]; then
		export GINWEBSER_NAME="ginwebser"
		export GINWEBSER="$1"
		export GINWEBSER_OBJS_DIR=
		export GINWEBSER_BIN="${RUNTIME_BIN}/${GINWEBSER_NAME}${BINSUFFIX}"
		export GINWEBSER_BIN_CLEAN="${GINWEBSER_BIN}_clean"
		export GINWEBSER_PHONY="GINWEBSER"
		export GINWEBSER_PHONY_DEV="GINWEBSER_DEV"
		export GINWEBSER_PHONY_CLEAN="GINWEBSER_CLEAN"
		export GINWEBSER_CFLAGS=
		export GINWEBSER_LDFLAGS=
		echo "GINWEBSER=${GINWEBSER}"
	fi

	if [ "${HAVE_05_GINWEBSERTEST}" = "1" ]; then
		export GINWEBSERTEST_NAME="ginwebser_test"
		export GINWEBSERTEST="$1"
		export GINWEBSERTEST_OBJS_DIR=
		export GINWEBSERTEST_BIN="${RUNTIME_BIN}/${GINWEBSERTEST_NAME}${BINSUFFIX}"
		export GINWEBSERTEST_BIN_CLEAN="${GINWEBSERTEST_BIN}_clean"
		export GINWEBSERTEST_PHONY="GINWEBSERTEST"
		export GINWEBSERTEST_PHONY_DEV="GINWEBSERTEST_DEV"
		export GINWEBSERTEST_PHONY_CLEAN="GINWEBSERTEST_CLEAN"
		export GINWEBSERTEST_CFLAGS=
		export GINWEBSERTEST_LDFLAGS=
		echo "GINWEBSERTEST=${GINWEBSERTEST}"
	fi

fi


