# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GRPCFTP_PHONY
	unset GRPCFTP_PHONY_DEV
	unset GRPCFTP_PHONY_CLEAN
	if [ "${HAVE_04_GRPCFTP}" = "1" ]; then
		export GRPCFTP="$1"
		export GRPCFTP_PHONY="GRPCFTP"
		export GRPCFTP_PHONY_DEV="GRPCFTP_DEV"
		export GRPCFTP_PHONY_CLEAN="GRPCFTP_CLEAN"
		echo "GRPCFTP=${GRPCFTP}"
		
		export BINGRPCFTPCLIENT_NAME="grpcftpclient"
		export BINGRPCFTPCLIENT="$1"
		export BINGRPCFTPCLIENT_OBJS_DIR=${RUNTIME_OBJS}${BINGRPCFTPCLIENT/${ROOT}/""}
		export BINGRPCFTPCLIENT_BIN="${RUNTIME_BIN}/${BINGRPCFTPCLIENT_NAME}${BINSUFFIX}"
		export BINGRPCFTPCLIENT_BIN_CLEAN="${BINGRPCFTPCLIENT_BIN}_clean"
		export BINGRPCFTPCLIENT_PHONY="BINGRPCFTPCLIENT"
		export BINGRPCFTPCLIENT_PHONY_DEV="BINGRPCFTPCLIENT_DEV"
		export BINGRPCFTPCLIENT_PHONY_CLEAN="BINGRPCFTPCLIENT_CLEAN"
		export BINGRPCFTPCLIENT_CFLAGS=
		export BINGRPCFTPCLIENT_LDFLAGS=
		echo "BINGRPCFTPCLIENT=${BINGRPCFTPCLIENT}"

		export BINGRPCFTPSERVER_NAME="grpcftpserver"
		export BINGRPCFTPSERVER="$1"
		export BINGRPCFTPSERVER_OBJS_DIR=${RUNTIME_OBJS}${BINGRPCFTPSERVER/${ROOT}/""}
		export BINGRPCFTPSERVER_BIN="${RUNTIME_BIN}/${BINGRPCFTPSERVER_NAME}${BINSUFFIX}"
		export BINGRPCFTPSERVER_BIN_CLEAN="${BINGRPCFTPSERVER_BIN}_clean"
		export BINGRPCFTPSERVER_PHONY="BINGRPCFTPSERVER"
		export BINGRPCFTPSERVER_PHONY_DEV="BINGRPCFTPSERVER_DEV"
		export BINGRPCFTPSERVER_PHONY_CLEAN="BINGRPCFTPSERVER_CLEAN"
		export BINGRPCFTPSERVER_CFLAGS=
		export BINGRPCFTPSERVER_LDFLAGS=
		echo "BINGRPCFTPSERVER=${BINGRPCFTPSERVER}"

		export HAVE_PBGRPCFTP=1
		export HAVE_GO_GRPCFTP=1
	fi
fi


