# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset STRINGSVC1_PHONY
	unset STRINGSVC1_PHONY_CLEAN
	if [ "${HAVE_07_GOKITSAMPLES}" = "1" ]; then
		export STRINGSVC1_NAME="stringsvc1"
		export STRINGSVC1="$1"
		export STRINGSVC1_OBJS_DIR=
		export STRINGSVC1_BIN="${RUNTIME_BIN}/${STRINGSVC1_NAME}${BINSUFFIX}"
		export STRINGSVC1_BIN_CLEAN="${STRINGSVC1_BIN}_clean"
		export STRINGSVC1_PHONY="STRINGSVC1"
		export STRINGSVC1_PHONY_DEV="STRINGSVC1_DEV"
		export STRINGSVC1_PHONY_CLEAN="STRINGSVC1_CLEAN"
		export STRINGSVC1_CFLAGS=
		export STRINGSVC1_LDFLAGS=
		echo "STRINGSVC1=${STRINGSVC1}"
	fi

fi


