# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GOPROTOBUFFER_PHONY
	unset GOPROTOBUFFER_PHONY_CLEAN
	if [ "${HAVE_GO_PROTOBUFFER}" = "1" ]; then
		export GOPROTOBUFFER_NAME="protobuffer_go"
		export GOPROTOBUFFER="$1"
		export GOPROTOBUFFER_OBJS_DIR=
		export GOPROTOBUFFER_BIN="${RUNTIME_BIN}/${GOPROTOBUFFER_NAME}${BINSUFFIX}"
		export GOPROTOBUFFER_BIN_CLEAN="${GOPROTOBUFFER_BIN}_clean"
		export GOPROTOBUFFER_PHONY="GOPROTOBUFFER"
		export GOPROTOBUFFER_PHONY_DEV="GOPROTOBUFFER_DEV"
		export GOPROTOBUFFER_PHONY_CLEAN="GOPROTOBUFFER_CLEAN"
		export GOPROTOBUFFER_CFLAGS=
		export GOPROTOBUFFER_LDFLAGS=
		echo "GOPROTOBUFFER=${GOPROTOBUFFER}"
	fi
fi


