# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GOGRPCFTPCLIENT_PHONY
	unset GOGRPCFTPCLIENT_PHONY_CLEAN
	if [ "${HAVE_GO_GRPCFTP}" = "1" ]; then
		export GOGRPCFTPCLIENT_NAME="grpcftpclient_go"
		export GOGRPCFTPCLIENT="$1"
		export GOGRPCFTPCLIENT_OBJS_DIR=
		export GOGRPCFTPCLIENT_BIN="${RUNTIME_BIN}/${GOGRPCFTPCLIENT_NAME}${BINSUFFIX}"
		export GOGRPCFTPCLIENT_BIN_CLEAN="${GOGRPCFTPCLIENT_BIN}_clean"
		export GOGRPCFTPCLIENT_PHONY="GOGRPCFTPCLIENT"
		export GOGRPCFTPCLIENT_PHONY_DEV="GOGRPCFTPCLIENT_DEV"
		export GOGRPCFTPCLIENT_PHONY_CLEAN="GOGRPCFTPCLIENT_CLEAN"
		export GOGRPCFTPCLIENT_CFLAGS=
		export GOGRPCFTPCLIENT_LDFLAGS=
		echo "GOGRPCFTPCLIENT=${GOGRPCFTPCLIENT}"

		export GOGRPCFTPSERVER_NAME="grpcftpserver_go"
		export GOGRPCFTPSERVER="$1"
		export GOGRPCFTPSERVER_OBJS_DIR=
		export GOGRPCFTPSERVER_BIN="${RUNTIME_BIN}/${GOGRPCFTPSERVER_NAME}${BINSUFFIX}"
		export GOGRPCFTPSERVER_BIN_CLEAN="${GOGRPCFTPSERVER_BIN}_clean"
		export GOGRPCFTPSERVER_PHONY="GOGRPCFTPSERVER"
		export GOGRPCFTPSERVER_PHONY_DEV="GOGRPCFTPSERVER_DEV"
		export GOGRPCFTPSERVER_PHONY_CLEAN="GOGRPCFTPSERVER_CLEAN"
		export GOGRPCFTPSERVER_CFLAGS=
		export GOGRPCFTPSERVER_LDFLAGS=
		echo "GOGRPCFTPSERVER=${GOGRPCFTPSERVER}"
	fi
fi

