# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset GOGRPCHELLOCLIENT_PHONY
	unset GOGRPCHELLOCLIENT_PHONY_CLEAN
	if [ "${HAVE_GO_GRPCHELLO}" = "1" ]; then
		export GOGRPCHELLOCLIENT_NAME="grpchelloclient_go"
		export GOGRPCHELLOCLIENT="$1"
		export GOGRPCHELLOCLIENT_OBJS_DIR=
		export GOGRPCHELLOCLIENT_BIN="${RUNTIME_BIN}/${GOGRPCHELLOCLIENT_NAME}${BINSUFFIX}"
		export GOGRPCHELLOCLIENT_BIN_CLEAN="${GOGRPCHELLOCLIENT_BIN}_clean"
		export GOGRPCHELLOCLIENT_PHONY="GOGRPCHELLOCLIENT"
		export GOGRPCHELLOCLIENT_PHONY_DEV="GOGRPCHELLOCLIENT_DEV"
		export GOGRPCHELLOCLIENT_PHONY_CLEAN="GOGRPCHELLOCLIENT_CLEAN"
		export GOGRPCHELLOCLIENT_CFLAGS=
		export GOGRPCHELLOCLIENT_LDFLAGS=
		echo "GOGRPCHELLOCLIENT=${GOGRPCHELLOCLIENT}"

		export GOGRPCHELLOSERVER_NAME="grpchelloserver_go"
		export GOGRPCHELLOSERVER="$1"
		export GOGRPCHELLOSERVER_OBJS_DIR=
		export GOGRPCHELLOSERVER_BIN="${RUNTIME_BIN}/${GOGRPCHELLOSERVER_NAME}${BINSUFFIX}"
		export GOGRPCHELLOSERVER_BIN_CLEAN="${GOGRPCHELLOSERVER_BIN}_clean"
		export GOGRPCHELLOSERVER_PHONY="GOGRPCHELLOSERVER"
		export GOGRPCHELLOSERVER_PHONY_DEV="GOGRPCHELLOSERVER_DEV"
		export GOGRPCHELLOSERVER_PHONY_CLEAN="GOGRPCHELLOSERVER_CLEAN"
		export GOGRPCHELLOSERVER_CFLAGS=
		export GOGRPCHELLOSERVER_LDFLAGS=
		echo "GOGRPCHELLOSERVER=${GOGRPCHELLOSERVER}"
	fi
fi

